server:
  port: 8081

spring:
  datasource:
    name: testa
    url: jdbc:mysql://43.143.29.193:3306/sale?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: shishishunxin
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB     # 可以上传的最大文件大小
      max-request-size: 100MB

  redis:
    host: 43.143.29.193
    port: 6379
    password: shishishunxin


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






